#!/bin/bash
# Manually installed packages
vim
vim-gnome
git
wmctrl	
beep			# Modify /etc/modprobe.d/blacklist.conf
font-manager
htop
udisks
vlc
testdisk
gddrescue
libttspico-utils	# TTS utility
libnss-myhostname	# Resolves system errors
xdotool			# Simulates keyboard events
tftp			# Useful utility for flashing devices
#imagemagick	# Using graphicsmagick instead
redshift-gtk
gparted
cruft
graphicsmagick
facter
calibre

# Install tilda version 1.2
git clone https://github.com/lanoxx/tilda.git
cd tilda
git checkout 3c5dd64 # Ver 1.2.4
# Redundant packages will automatically skipped
sudo apt-get install git automake libgtk-3-dev libvte-2.90-dev libconfuse-dev
sudo apt-get install gettext automake autoconf autopoint
./autogen.sh --prefix=/usr
make --silent
sudo make install

# Fish shell
sudo apt-get install fish
chsh -s /usr/bin/fish	# Sets default shell

# Ubuntu Make installation instructions for Ubuntu 14.04
# Android development environment installation
sudo add-apt-repository ppa:ubuntu-desktop/ubuntu-make
sudo apt-get update
sudo apt-get install ubuntu-make
sudo umake android

# Latex
#texmaker		# --no-install-recommends
texlive-base
texlive-latex-base
texlive-latex-extra	# --no-install-recommends

# Nautilus
# Restart nautilus with 'nautilus -q'
nautilus-open-terminal
nautilus-actions

# Appearance
flatabulous-theme
ultra-flat-icons
unity-tweak-tool

# Fonts
# Fonts are installed to ~/.local/share/fonts or ~/.fonts
Consolas
Hack
Inconsolata
#Monospace
Adobe Source Code Pro
#Roboto Mono
#Droid Sans Mono
#Anonymous Pro
#Monaco
#Terminus
