#!/bin/bash
# Color pallete: https://design.ubuntu.com/brand/colour-palette
# Written by Chad Sebesta

# Get screen resolution
RESOLUTION="$( xdpyinfo | awk '/dimensions/{print $2}' )"

# Create background
gm convert \
	-size $RESOLUTION xc:#2C001E \
	/tmp/sombra.png

# Overlay skull
gm composite \
	-gravity center \
	$HOME/Pictures/skull.png \
	/tmp/sombra.png \
	/tmp/sombra.png

# Set background
gsettings set org.gnome.desktop.background \
picture-uri file:///tmp/sombra.jpg

## Hide the unity launcher
#gsettings set org.compiz.unityshell:/org/compiz/profiles/unity/plugins/unityshell/ launcher-hide-mode 1

# Witty message
ICN="$HOME/Pictures/skull.png"
notify-send -u critical -i $ICN 'HACKED'
